resume/urls.py
from django.urls import path
from . import views

app_name = 'resume'

urlpatterns = [
    path('cv/', views.home, name='home'),
    path('', views.home, name='home'),
    path('cv/about_me/', views.about_me, name='about_me'),
    path('cv/website/', views.website, name='website'),
    path('cv/contact/', views.mail, name='contact'),
    path('cv/skills/', views.skills, name = 'skills'),
    path('cv/back-end/', views.back, name = 'back'),
    path('cv/skills/<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name = 'blog_detail'),
    path('cv/skills/tag/<slug:tag_slug>/', views.skills, name='post_list_by_tag'),

            ]

resume/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):

    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='blog_posts')
    #body = models.TextField()
    body=RichTextField(blank=True, null = True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('resume:blog_detail', args = [self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title       

resume/forms.py
from django import forms

class EmailPostForm(forms.Form):
        name = forms.CharField(max_length=50,label='Name  ')
        email = forms.EmailField(label='Email  ')
        notice = forms.CharField(required=True, widget=forms.Textarea)

resume/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm
from django.core.mail import send_mail


def home(request):
    return render(request, 'home2.html',{} )

def hobbies(request):
    return render(request, 'hobbies.html',{} )

def about_me(request):
    return render(request, 'about_me.html',{} )

def website(request):
    return render(request, 'website.html',{} )
    
def contact(request):
    return render(request, 'contact.html',{} )


def back(request):
    return render(request, 'back-end.html',{} )


def blog(request):
    return render(request, 'blog.html',{} )



def post_detail(request, year, month, day, post):
    print(request)
    post = get_object_or_404(Post, slug = post, status = 'published', publish__year = year, publish__month = month, publish__day = day)
    print(post)
    template = 'blog_detail.html'
    context = {'post': post}
    return render(request, template, context)


def mail(request):
    sent = False
    if request.method == 'POST':
        # Formularz został wysłany.
        form = EmailPostForm(request.POST)
        if form.is_valid():
        # Weryfikacja pól formularza zakończyła się powodzeniem...
            cd = form.cleaned_data
            dane = 'Została wysłana wiadomość z servera DJANGO od urzytkownika {} o adresie email  {}   OK.  '.format(cd['name'],cd['email']) 
        # ... więc można wysłać wiadomość e-mail.
            send_mail(dane, cd['notice'], '2021resumecv@gmail.com', ['2021resumecv@gmail.com'])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'contact.html', {'form': form, 'sent':sent})

def skills(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3) # Trzy posty na każdej stronie.
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'page': page, 'posts': posts, 'tag':tag}
    return render(request, 'skills.html', context )

resume/templates/about_me.html
{% extends 'base.html' %}

{% block content %}
<h2 style='text-align: center;font-size: 22x;' >Welcome</h2>
<h2 style='text-align: left;'>
<br> &emsp;&emsp;Electrical engineer with 4 years of experience in supervising production lines in the private sector. 
Since I can remember, I have been passionate about IT and electrics.
Also my passion is learning and skills new skills and sharing knowledge with others.<br>
&emsp;&emsp;I am an inquisitive, optimistic and sincere person, having no problem with making new friendships.
I systematically raise my qualifications and deepen my knowledge. In my spare time, I practice Python at Codewars.com and deepen my knowledge of SBC (Raspberry, Odroid, Odyssey) .
<br>
On the last day of my life I would see the Lord of the rings again :-)</h2>
{% endblock %}
{% block title %} About me {% endblock %}

resume/templates/back-end.html
{% extends 'base.html' %}

{% block content %}
<h2 style='text-align: left;'> &emsp;I am interested in developing as a Junior Python Developer and I think that I will
be great in this role. I speak English at the B1 level, communication and learning new
tools from technical documentation is not a problem for me. I have been using Linux
systems for years so I am well versed in handling the terminal and installing from
repositories.<br>

&emsp;During my studies at the Kielce University of Technology, I had contact with:
C, C ++ and bash, but Python3, due to the syntax of the library and objectivity, I wanted
to develop to perfection.<br>
&emsp;I am familiar with Pandas, Numpy, Matplotlib and I am currently learning the
Django framework. Already during my studies, I had contact with MySQL and
PostgreSQL databases. I use PyCharm and Visual Studio Code environments on a daily
basis.<br>
I am currently learning REST framework, Redis, Celery and other framework for Django.<br>
&emsp;I am eager to expand my knowledge of tests, GIT version control system Docker
and code optimization.
I am an inquisitive, optimistic and sincere person, having no problem with making
new friendships.<br>
&emsp;In my spare time, I practice Python at Codewars.com and deepen my knowledge
of SBC (Raspberry, Odroid, Odyssey)<br>
In order to gain new knowledge and skills, I can start working with you free of
charge during the trial period with the possibility of working immediately.<br>
&emsp;I will be very happy to meet you at the interview and answer all questions
regarding of my candidacy.</h2>
{% endblock %}
{% block title %} Back-end {% endblock %}

resume/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<link href="{% static "css/style6.css" %}" rel="stylesheet">
<title>
  {% block title %}
  {% endblock %} 
</title>
</head>
<body>
  <div id="styl2">  <h1>Zawisza Karol</h1>
    <p class='title'><b>MSc in Electrical Engineering specialization Automation</b></p></div> 
<br>
<ul>
  <li><a href="/cv/">Resume</a></li>
  <li><a href="/cv/about_me/">About me</a></li>
  <li><a href="/cv/skills/">&nbsp&nbspSkills&nbsp&nbsp</a></li>
  <li><a href="/cv/back-end/">Back-end</a></li>
  <li><a href="/cv/website/">Website</a></li>
  <li style="float:right"><a class="active" href="/cv/contact/">Contact</a></li>
</ul>
<br><br>

<div id="styl1">
{% block content %}
{% endblock %}
</div>

</body>
</html>

resume/templates/blog_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ post.title }}</h1>

<p class="article">{{ post.body|safe }}</p>
{% endblock %}

resume/templates/contact.html
{% extends "base.html" %}
{% block content %}
{% if sent %}
<h1>Message has been sent.</h1>

{% else %}
<h1>Information</h1>
<p>Phone:   570-096-077</p>
<p>Email:   karrol900@gmail.com</p>
<a href="https://www.linkedin.com/in/karol-zawisza" target="_blank" >www.linkedin.com/in/karol-zawisza</a>
<h1>Send me a message</h1>
<form action="." method="post">
{{ form.as_p}}
{% csrf_token %}
<input type="submit" value="Send">
</form>
{% endif %}
{% endblock %}
{% block title %} Contact {% endblock %}

resume/templates/home2.html
{% extends 'base.html' %}
xxxxxxxxxxxxxxx
{% block content %}
  <h2>Education</h2>
  <p style='font-size: 20px;'><i>25/02/2015 – 19/07/2016</i> <b> Kielce University of Technology</b></p>
  <p style='font-size: 20px;'>MSc in Electrical specialization Automation</p>
  <p style='font-size: 20px;'><i>01/09/2011 – 15/02/2014</i> <b>Kielce University of Technology</b></p>
  <p style='font-size: 20px;'>Enginneering Electrical specialization Automation</p>
  <hr style='color:rgb(255, 255, 255)'>
  <h2>Work experience</h2>
  <p style='font-size: 20px;'><i>06/12/2017 – 31/03/2020</i>    <b>   Specialist electrician Strunobet Kuzki</b><br>
  -control and supervision of the production and supply process<br>
  -preparation of technical and technological documentation
  -contact with international clients<br>
  -creating 2D CAD diagrams and 3D models <br>
  -designing power systems in accordance with customer requirements<br></p>
  <p style='font-size: 20px;'><i>15/09/2016 – 30/11/2017</i> <b> Automation foreman Cerrad Starachowice</b> <br>
    -supervising machines and devices in terms of electromechanics<br>
    -diagnosis of failures and their removal<br>
    -control and supervision of the production process in SCADA software<br></p>
  <p style='font-size: 20px;'><i>15/03/2013 – 15/07/2017</i> <b> Bartender Ultraviolet Kielce</b> <br></p>
  <p style='font-size: 20px;'><i>01/06/2010 – 30/08/2010</i> <b>Helper of electrician Z.P.U.E Włoszczowa</b><br></p>
  <hr style='color:rgb(255, 255, 255)'>
  <h2>Additional information</h2>
  <p style='font-size: 20px;'>Permissions SEP 1kV E and D, SEP 45kV E</p>
  <p style='font-size: 20px;'> Language: English B1 Russian A1</p>
  <p style='font-size: 20px;'> Very good knowledge of the software CAD (Bricscad 2D and 3D)</p>
  <p style='font-size: 20px;'> Very good knowledge of the software Microsoft Office</p>
  
  {% endblock %}

  {% block title %} Resume {% endblock %}

resume/templates/pagination.html
<div class="align-items: center">
    <span class="step-links">
        <br>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

resume/templates/skills.html
{% extends 'base.html' %}
{% block content %}
<h1>Skills</h1>
<ul>
    <li><a href="/cv/skills/tag/automation/">Automation</a></li>
    <li><a href="/cv/skills/tag/cad/">&nbsp&nbspCAD&nbsp</a></li>
    <li><a href="/cv/skills/tag/django/">Django</a></li>
    <li><a href="/cv/skills/tag/english/">English</a></li>
    <li><a href="/cv/skills/tag/electric/">Electric</a></li>
    <li><a href="/cv/skills/tag/linux/">Linux</a></li>
    <li><a href="/cv/skills/tag/python/">Python</a></li>
    <li><a href="/cv/skills/tag/raspberry/">Raspberry Pi</a></li>
    <li style="float:right"><a class="active" href="/cv/skills/">&nbspAll&nbsp</a></li>
  </ul>
<br>
{% for post in posts %}
<h2 style='text-align:left'>
<a href="{{ post.get_absolute_url }}">   
{{ post.title }}
</a>
</h2>
<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
    <a href="{% url "resume:post_list_by_tag" tag.slug %}">
    {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
{% endfor %}
</p>
{{ post.body|truncatewords:50|safe }}
<br>
{% endfor %}
<div style="align-items: center;">
{% include "pagination.html" with page=posts %}
</div>
{% endblock %}

{% block title %} Skills {% endblock %}

resume/templates/website.html
{% extends 'base.html' %}
xxxxxxxxxxxxxxx
{% block content %}
<h2>This page was created with the Django framework on Raspberry Pi 4 single-board computers with system Ubuntu<br>
    This website is currently running on a pythonanywhere server.</h2> 
{% endblock %}
{% block title %} Website {% endblock %}